Repository La-Fresca/la-fresca-backend, pull requests merged in 2024-12, with the labels that each got.

#154 System log completed
  .gitignore
  src/main/java/org/lafresca/lafrescabackend/Controllers/SystemLogController.java
  src/main/java/org/lafresca/lafrescabackend/DTO/AddedFeatureDTO.java
  src/main/java/org/lafresca/lafrescabackend/Services/BranchService.java
  src/main/java/org/lafresca/lafrescabackend/Services/CartService.java
  src/main/java/org/lafresca/lafrescabackend/Services/CategoryService.java
  src/main/java/org/lafresca/lafrescabackend/Services/ComplaintService.java
  src/main/java/org/lafresca/lafrescabackend/Services/DiscountService.java
  src/main/java/org/lafresca/lafrescabackend/Services/EmailService.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodComboService.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodItemService.java
  src/main/java/org/lafresca/lafrescabackend/Services/ForgotPasswordService.java
  src/main/java/org/lafresca/lafrescabackend/Services/MonthlyBranchStatService.java
  src/main/java/org/lafresca/lafrescabackend/Services/NotificationService.java
  src/main/java/org/lafresca/lafrescabackend/Services/OrderService.java
  src/main/java/org/lafresca/lafrescabackend/Services/StockCollectionService.java
  src/main/java/org/lafresca/lafrescabackend/Services/StockService.java
  src/main/java/org/lafresca/lafrescabackend/Services/SystemLogService.java
  src/main/java/org/lafresca/lafrescabackend/Services/UserDetailsServiceImp.java
  src/main/java/org/lafresca/lafrescabackend/Services/UserService.java
  src/main/java/org/lafresca/lafrescabackend/Validations/FoodAmountValidation.java
  src/main/resources/logback-spring.xml
Labels: documentation, feat

#155 add new item to cart bug fixed
  src/main/java/org/lafresca/lafrescabackend/Services/CartService.java
Labels: fix

#156 fix: Discount Functionality
  src/main/java/org/lafresca/lafrescabackend/Controllers/DiscountController.java
  src/main/java/org/lafresca/lafrescabackend/DTO/DiscountDTO.java
  src/main/java/org/lafresca/lafrescabackend/Services/DiscountService.java
Labels: fix

#157 fix: View discount for top-level manager
  src/main/java/org/lafresca/lafrescabackend/Controllers/DiscountController.java
  src/main/java/org/lafresca/lafrescabackend/Services/DiscountService.java
Labels: fix

#159 Get served and assigned orders by cafe Id api created
  src/main/java/org/lafresca/lafrescabackend/Controllers/OrderController.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/OrderRepository.java
  src/main/java/org/lafresca/lafrescabackend/Services/OrderService.java
  src/main/java/org/lafresca/lafrescabackend/Services/UserService.java
Labels: feat

#160 Update
  src/main/java/org/lafresca/lafrescabackend/Configuration/SecurityConfig.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/OrderController.java
Labels: refactor

#161 Assigned to waiter orders bug fixed
  src/main/java/org/lafresca/lafrescabackend/Services/OrderService.java
Labels: fix

#162 Delivery Person dashbord api
  src/main/java/org/lafresca/lafrescabackend/Configuration/SecurityConfig.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/OrderController.java
  src/main/java/org/lafresca/lafrescabackend/DTO/DeliveryPersonDashbordDTO.java
Labels: enhancement

#163 fix: user registration
  src/main/java/org/lafresca/lafrescabackend/Services/UserService.java
Labels: fix

#164 User controller status codes added
  src/main/java/org/lafresca/lafrescabackend/Controllers/UserController.java
  src/main/java/org/lafresca/lafrescabackend/Services/UserService.java
Labels: fix
