Repository La-Fresca/la-fresca-backend, pull requests merged in 2024-08, with the labels that each got.

#105 fix: discount add
  src/main/java/org/lafresca/lafrescabackend/Controllers/DiscountController.java
  src/main/java/org/lafresca/lafrescabackend/Models/Discount.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/FoodComboRepository.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/FoodItemRepository.java
  src/main/java/org/lafresca/lafrescabackend/Services/DiscountService.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodComboService.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodItemService.java
Labels: enhancement, fix

#106 fix: Branch
  src/main/java/org/lafresca/lafrescabackend/Models/Branch.java
  src/main/java/org/lafresca/lafrescabackend/Models/Income.java
  src/main/java/org/lafresca/lafrescabackend/Models/IncomeCost.java
  src/main/java/org/lafresca/lafrescabackend/Services/BranchService.java
Labels: fix

#107 Order automatically assigned to waiter/delivery person
  src/main/java/org/lafresca/lafrescabackend/Controllers/DiscountController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/OrderController.java
  src/main/java/org/lafresca/lafrescabackend/Models/Branch.java
  src/main/java/org/lafresca/lafrescabackend/Models/Discount.java
  src/main/java/org/lafresca/lafrescabackend/Models/Income.java
  src/main/java/org/lafresca/lafrescabackend/Models/IncomeCost.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/FoodComboRepository.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/FoodItemRepository.java
  src/main/java/org/lafresca/lafrescabackend/Services/BranchService.java
  src/main/java/org/lafresca/lafrescabackend/Services/DiscountService.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodComboService.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodItemService.java
  src/main/java/org/lafresca/lafrescabackend/Services/OrderService.java
Labels: feat

#109 Update view all food combos and food items
  src/main/java/org/lafresca/lafrescabackend/Controllers/FoodComboController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/FoodItemController.java
  src/main/java/org/lafresca/lafrescabackend/Models/Category.java
  src/main/java/org/lafresca/lafrescabackend/Models/FoodCombo.java
  src/main/java/org/lafresca/lafrescabackend/Models/FoodItem.java
  src/main/java/org/lafresca/lafrescabackend/Models/Income.java
  src/main/java/org/lafresca/lafrescabackend/Models/Stock.java
  src/main/java/org/lafresca/lafrescabackend/Models/StockCollection.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/FoodComboRepository.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/FoodItemRepository.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/StockCollectionRepository.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/StockRepository.java
  src/main/java/org/lafresca/lafrescabackend/Services/CategoryService.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodComboService.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodItemService.java
  src/main/java/org/lafresca/lafrescabackend/Services/StockCollectionService.java
  src/main/java/org/lafresca/lafrescabackend/Services/StockService.java
Labels: enhancement, fix

#111 fix: structure of the stock and stock collection
  src/main/java/org/lafresca/lafrescabackend/Models/Stock.java
  src/main/java/org/lafresca/lafrescabackend/Models/StockCollection.java
  src/main/java/org/lafresca/lafrescabackend/Services/StockService.java
Labels: enhancement, fix
