Repository La-Fresca/la-fresca-backend, pull requests merged in 2024-07, with the labels that each got.

#47 Update food item class with rating and set cross origin
  src/main/java/org/lafresca/lafrescabackend/Controllers/FoodItemController.java
  src/main/java/org/lafresca/lafrescabackend/DTO/FoodItemDTO.java
  src/main/java/org/lafresca/lafrescabackend/DTO/FoodItemDTOMapper.java
  src/main/java/org/lafresca/lafrescabackend/Models/FoodItem.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodItemService.java
Labels: feat

#51 Retrieve all by deleted:0
  src/main/java/org/lafresca/lafrescabackend/Repositories/FoodItemRepository.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodItemService.java
Labels: feat, fix

#54 fix: Added Cross Origin Annotations to Branch, Category and Discount …
  src/main/java/org/lafresca/lafrescabackend/Controllers/BranchController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/CategoryController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/DiscountController.java
Labels: fix

#55 Added Cross Origin Annotations to Branch, Category and Discount Controllers
  src/main/java/org/lafresca/lafrescabackend/Controllers/BranchController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/CategoryController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/DiscountController.java
Labels: fix

#56 fix: discount status error
  src/main/java/org/lafresca/lafrescabackend/DTO/FoodItemDTO.java
  src/main/java/org/lafresca/lafrescabackend/DTO/FoodItemDTOMapper.java
  src/main/java/org/lafresca/lafrescabackend/Models/FoodItem.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/FoodItemRepository.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodItemService.java
Labels: fix

#57 fix: discount status error
  src/main/java/org/lafresca/lafrescabackend/Services/FoodItemService.java
Labels: fix

#58 feat: multiple category selection
  src/main/java/org/lafresca/lafrescabackend/DTO/FoodItemDTO.java
  src/main/java/org/lafresca/lafrescabackend/Models/FoodItem.java
Labels: feat

#60 fix: CORS
  src/main/java/org/lafresca/lafrescabackend/Controllers/FoodComboController.java
Labels: fix

#63 auth update
  src/main/java/org/lafresca/lafrescabackend/Configuration/AuthenticationService.java
  src/main/java/org/lafresca/lafrescabackend/Configuration/JwtService.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/AuthenticationController.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/TokenRepository.java
Labels: feat

#68 fix: Stock CRUD Functionalities
  src/main/java/org/lafresca/lafrescabackend/Services/StockService.java
Labels: fix

#64 update
  src/main/java/org/lafresca/lafrescabackend/Configuration/JwtService.java
  src/main/java/org/lafresca/lafrescabackend/Configuration/SecurityConfig.java
Labels: bug

#69 fix: Add New Category Functionality
  src/main/java/org/lafresca/lafrescabackend/Repositories/CategoryRepository.java
  src/main/java/org/lafresca/lafrescabackend/Services/CategoryService.java
Labels: fix

#70 fix: Food Item, Stock CRUD Functionalities
  src/main/java/org/lafresca/lafrescabackend/Controllers/FoodItemController.java
  src/main/java/org/lafresca/lafrescabackend/DTO/FoodItemDTO.java
  src/main/java/org/lafresca/lafrescabackend/DTO/FoodItemDTOMapper.java
  src/main/java/org/lafresca/lafrescabackend/Models/Discount.java
  src/main/java/org/lafresca/lafrescabackend/Models/FoodItem.java
  src/main/java/org/lafresca/lafrescabackend/Models/Stock.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodItemService.java
  src/main/java/org/lafresca/lafrescabackend/Services/StockService.java
Labels: feat, fix

#71 fix: Food Item DTO and DTO Mapper
  src/main/java/org/lafresca/lafrescabackend/DTO/FoodItemDTO.java
  src/main/java/org/lafresca/lafrescabackend/DTO/FoodItemDTOMapper.java
Labels: fix

#72 fix: Food Combo CRUD
  src/main/java/org/lafresca/lafrescabackend/Controllers/BranchController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/CartController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/DiscountController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/StockController.java
  src/main/java/org/lafresca/lafrescabackend/Models/FoodCombo.java
  src/main/java/org/lafresca/lafrescabackend/Models/Order.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodComboService.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodItemService.java
Labels: fix

#74 fix: Cart and Stock Collection CRUDs
  src/main/java/org/lafresca/lafrescabackend/Controllers/StockCollectionController.java
  src/main/java/org/lafresca/lafrescabackend/Models/Cart.java
  src/main/java/org/lafresca/lafrescabackend/Models/CartItem.java
  src/main/java/org/lafresca/lafrescabackend/Models/CustomFeature.java
  src/main/java/org/lafresca/lafrescabackend/Models/Stock.java
  src/main/java/org/lafresca/lafrescabackend/Models/StockCollection.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/StockCollectionRepository.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/StockRepository.java
  src/main/java/org/lafresca/lafrescabackend/Services/CartService.java
  src/main/java/org/lafresca/lafrescabackend/Services/StockCollectionService.java
  src/main/java/org/lafresca/lafrescabackend/Services/StockService.java
Labels: feat, fix

#73 Assign order
  src/main/java/org/lafresca/lafrescabackend/Configuration/AuthenticationService.java
  src/main/java/org/lafresca/lafrescabackend/Configuration/JwtService.java
  src/main/java/org/lafresca/lafrescabackend/Configuration/SecurityConfig.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/AuthenticationController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/FoodComboController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/FoodItemController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/OrderController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/UserController.java
  src/main/java/org/lafresca/lafrescabackend/DTO/FoodItemDTO.java
  src/main/java/org/lafresca/lafrescabackend/DTO/FoodItemDTOMapper.java
  src/main/java/org/lafresca/lafrescabackend/DTO/OrderStatusChangeRequest.java
  src/main/java/org/lafresca/lafrescabackend/DTO/UserDTO.java
  src/main/java/org/lafresca/lafrescabackend/Models/Discount.java
  src/main/java/org/lafresca/lafrescabackend/Models/FoodItem.java
  src/main/java/org/lafresca/lafrescabackend/Models/Stock.java
  src/main/java/org/lafresca/lafrescabackend/Models/User.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/CategoryRepository.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/OrderRepository.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/TokenRepository.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/UserRepository.java
  src/main/java/org/lafresca/lafrescabackend/Services/CategoryService.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodItemService.java
  src/main/java/org/lafresca/lafrescabackend/Services/OrderService.java
  src/main/java/org/lafresca/lafrescabackend/Services/StockService.java
  src/main/java/org/lafresca/lafrescabackend/Services/UserService.java
Labels: feat

#75 fix : Food Item, Food Combo, Cart
  src/main/java/org/lafresca/lafrescabackend/Models/Cart.java
  src/main/java/org/lafresca/lafrescabackend/Models/FoodCombo.java
  src/main/java/org/lafresca/lafrescabackend/Models/FoodItem.java
  src/main/java/org/lafresca/lafrescabackend/Services/CartService.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodComboService.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodItemService.java
  src/main/java/org/lafresca/lafrescabackend/Services/StockCollectionService.java
Labels: fix

#76 feat: Logical Deletion for Food Combo, Branch, Stock and Stock Collection
  src/main/java/org/lafresca/lafrescabackend/Controllers/BranchController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/FoodComboController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/StockCollectionController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/StockController.java
  src/main/java/org/lafresca/lafrescabackend/Models/Branch.java
  src/main/java/org/lafresca/lafrescabackend/Models/Stock.java
  src/main/java/org/lafresca/lafrescabackend/Models/StockCollection.java
  src/main/java/org/lafresca/lafrescabackend/Services/BranchService.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodComboService.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodItemService.java
  src/main/java/org/lafresca/lafrescabackend/Services/StockCollectionService.java
  src/main/java/org/lafresca/lafrescabackend/Services/StockService.java
Labels: feat, fix

#78 Fix: Order handling
  src/main/java/org/lafresca/lafrescabackend/Controllers/OrderController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/UserController.java
  src/main/java/org/lafresca/lafrescabackend/DTO/OrderStatusChangeRequest.java
  src/main/java/org/lafresca/lafrescabackend/DTO/UserDTO.java
  src/main/java/org/lafresca/lafrescabackend/Models/Order.java
  src/main/java/org/lafresca/lafrescabackend/Models/Stock.java
  src/main/java/org/lafresca/lafrescabackend/Models/User.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/OrderRepository.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/UserRepository.java
  src/main/java/org/lafresca/lafrescabackend/Services/OrderService.java
  src/main/java/org/lafresca/lafrescabackend/Services/StockService.java
  src/main/java/org/lafresca/lafrescabackend/Services/UserService.java
Labels: enhancement, fix

#80 fix: add to cart
  src/main/java/org/lafresca/lafrescabackend/Models/Cart.java
  src/main/java/org/lafresca/lafrescabackend/Models/CartItemFeature.java
  src/main/java/org/lafresca/lafrescabackend/Services/CartService.java
Labels: fix

#81 Stock Collection Logical Deletion and Get Stock by Name
  src/main/java/org/lafresca/lafrescabackend/Controllers/StockController.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/StockRepository.java
  src/main/java/org/lafresca/lafrescabackend/Services/StockCollectionService.java
  src/main/java/org/lafresca/lafrescabackend/Services/StockService.java
Labels: feat, fix

#83 fix: Food Combo, Stock, Stock Collection Get All Method
  src/main/java/org/lafresca/lafrescabackend/Repositories/FoodComboRepository.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/StockCollectionRepository.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/StockRepository.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodComboService.java
  src/main/java/org/lafresca/lafrescabackend/Services/StockCollectionService.java
  src/main/java/org/lafresca/lafrescabackend/Services/StockService.java
Labels: fix

#84 fix: Stock Collection Creation
  src/main/java/org/lafresca/lafrescabackend/Services/StockCollectionService.java
Labels: fix

#85 Kitchen and the
  src/main/java/org/lafresca/lafrescabackend/Configuration/JwtService.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/BranchController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/FoodComboController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/OrderController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/StockCollectionController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/StockController.java
  src/main/java/org/lafresca/lafrescabackend/DTO/ItemStatusChangeDTO.java
  src/main/java/org/lafresca/lafrescabackend/Models/Cart.java
  src/main/java/org/lafresca/lafrescabackend/Models/CartItemFeature.java
  src/main/java/org/lafresca/lafrescabackend/Models/FoodItem.java
  src/main/java/org/lafresca/lafrescabackend/Models/OrderFood.java
  src/main/java/org/lafresca/lafrescabackend/Models/OrderStatus.java
  src/main/java/org/lafresca/lafrescabackend/Models/Stock.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/OrderRepository.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/StockCollectionRepository.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/StockRepository.java
  src/main/java/org/lafresca/lafrescabackend/Services/BranchService.java
  src/main/java/org/lafresca/lafrescabackend/Services/CartService.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodComboService.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodItemService.java
  src/main/java/org/lafresca/lafrescabackend/Services/OrderService.java
  src/main/java/org/lafresca/lafrescabackend/Services/StockCollectionService.java
  src/main/java/org/lafresca/lafrescabackend/Services/StockService.java
Labels: enhancement

#86 updateOrderStatus and deliveryOrderStatus functions added
  src/main/java/org/lafresca/lafrescabackend/Configuration/AuthenticationService.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/OrderController.java
  src/main/java/org/lafresca/lafrescabackend/DTO/ItemStatusChangeDTO.java
  src/main/java/org/lafresca/lafrescabackend/Services/OrderService.java
Labels: enhancement, feat

#88 fix: Get All Food Combos
  src/main/java/org/lafresca/lafrescabackend/Controllers/FoodComboController.java
  src/main/java/org/lafresca/lafrescabackend/Models/FoodCombo.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/FoodItemRepository.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodComboService.java
Labels: fix

#87 update
  src/main/java/org/lafresca/lafrescabackend/Controllers/OrderController.java
  src/main/java/org/lafresca/lafrescabackend/Models/OrderFood.java
  src/main/java/org/lafresca/lafrescabackend/Services/OrderService.java
Labels: enhancement

#89 Kitchen
  src/main/java/org/lafresca/lafrescabackend/Configuration/AuthenticationService.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/FoodComboController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/OrderController.java
  src/main/java/org/lafresca/lafrescabackend/DTO/AddedFeatureDTO.java
  src/main/java/org/lafresca/lafrescabackend/DTO/OrderItemDTO.java
  src/main/java/org/lafresca/lafrescabackend/DTO/OrderRequestDTO.java
  src/main/java/org/lafresca/lafrescabackend/Models/Cart.java
  src/main/java/org/lafresca/lafrescabackend/Models/FoodCombo.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/FoodComboRepository.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/FoodItemRepository.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/StockCollectionRepository.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/StockRepository.java
  src/main/java/org/lafresca/lafrescabackend/Services/CartService.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodComboService.java
  src/main/java/org/lafresca/lafrescabackend/Services/OrderService.java
  src/main/java/org/lafresca/lafrescabackend/Services/StockCollectionService.java
  src/main/java/org/lafresca/lafrescabackend/Services/StockService.java
Labels: feat
