Repository La-Fresca/la-fresca-backend, pull requests merged in 2024-11, with the labels that each got.

#125 Navbar name
  pom.xml
  src/main/java/org/lafresca/lafrescabackend/Configuration/JwtService.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/BranchController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/CartController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/CategoryController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/EmailController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/FoodComboController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/FoodItemController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/StockCollectionController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/StockController.java
  src/main/java/org/lafresca/lafrescabackend/DTO/CategoryDTO.java
  src/main/java/org/lafresca/lafrescabackend/DTO/CategoryDTOMapper.java
  src/main/java/org/lafresca/lafrescabackend/DTO/Request/BranchRequestDTO.java
  src/main/java/org/lafresca/lafrescabackend/DTO/Request/FoodComboRequestDTO.java
  src/main/java/org/lafresca/lafrescabackend/DTO/Request/FoodItemRequestDTO.java
  src/main/java/org/lafresca/lafrescabackend/DTO/Request/StockCollectionRequestDTO.java
  src/main/java/org/lafresca/lafrescabackend/DTO/Request/StockRequestDTO.java
  src/main/java/org/lafresca/lafrescabackend/DTO/StockDTO.java
  src/main/java/org/lafresca/lafrescabackend/DTO/StockDTOMapper.java
  src/main/java/org/lafresca/lafrescabackend/DTO/ValidationErrorResponse.java
  src/main/java/org/lafresca/lafrescabackend/Exceptions/GlobalExceptionHandler.java
  src/main/java/org/lafresca/lafrescabackend/Models/EmailStructure.java
  src/main/java/org/lafresca/lafrescabackend/Models/FoodCombo.java
  src/main/java/org/lafresca/lafrescabackend/Models/Stock.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/CategoryRepository.java
  src/main/java/org/lafresca/lafrescabackend/Services/BranchService.java
  src/main/java/org/lafresca/lafrescabackend/Services/CategoryService.java
  src/main/java/org/lafresca/lafrescabackend/Services/EmailService.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodComboService.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodItemService.java
  src/main/java/org/lafresca/lafrescabackend/Services/StockCollectionService.java
  src/main/java/org/lafresca/lafrescabackend/Services/StockService.java
  src/main/java/org/lafresca/lafrescabackend/Validations/Impl/AmountValidator.java
  src/main/java/org/lafresca/lafrescabackend/Validations/Impl/CostValidator.java
  src/main/java/org/lafresca/lafrescabackend/Validations/Impl/ExpiryDateValidator.java
  src/main/java/org/lafresca/lafrescabackend/Validations/Impl/PriceValidator.java
  src/main/java/org/lafresca/lafrescabackend/Validations/ValidAmount.java
  src/main/java/org/lafresca/lafrescabackend/Validations/ValidCost.java
  src/main/java/org/lafresca/lafrescabackend/Validations/ValidExpiryDate.java
  src/main/java/org/lafresca/lafrescabackend/Validations/ValidPrice.java
  src/main/resources/application.properties
Labels: enhancement

#129 availableBranchManagers api and basic branch details
  src/main/java/org/lafresca/lafrescabackend/Controllers/BranchController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/OrderController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/UserController.java
  src/main/java/org/lafresca/lafrescabackend/DTO/BranchStat.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/OrderRepository.java
  src/main/java/org/lafresca/lafrescabackend/Services/BranchService.java
  src/main/java/org/lafresca/lafrescabackend/Services/OrderService.java
  src/main/java/org/lafresca/lafrescabackend/Services/UserService.java
Labels: feat

#130 Branch details bug fixed
  build.cmd
  run.cmd
  src/main/java/org/lafresca/lafrescabackend/Configuration/JwtService.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/UserRepository.java
  src/main/java/org/lafresca/lafrescabackend/Services/BranchService.java
Labels: bug

#133 Food item and combo approval process - top level anager
  package-lock.json
  pom.xml
  src/main/java/org/lafresca/lafrescabackend/Configuration/JwtService.java
  src/main/java/org/lafresca/lafrescabackend/Configuration/WebSocketConfig.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/BranchController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/FoodComboController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/FoodItemController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/NotificationController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/OrderController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/StockCollectionController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/StockController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/UserController.java
  src/main/java/org/lafresca/lafrescabackend/DTO/BranchStat.java
  src/main/java/org/lafresca/lafrescabackend/DTO/FoodItemDTO.java
  src/main/java/org/lafresca/lafrescabackend/DTO/FoodItemDTOMapper.java
  src/main/java/org/lafresca/lafrescabackend/DTO/Request/BranchRequestDTO.java
  src/main/java/org/lafresca/lafrescabackend/DTO/StockDTO.java
  src/main/java/org/lafresca/lafrescabackend/Models/Branch.java
  src/main/java/org/lafresca/lafrescabackend/Models/BranchStatus.java
  src/main/java/org/lafresca/lafrescabackend/Models/FoodCombo.java
  src/main/java/org/lafresca/lafrescabackend/Models/FoodItem.java
  src/main/java/org/lafresca/lafrescabackend/Models/Notification.java
  src/main/java/org/lafresca/lafrescabackend/Models/StockCollection.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/FoodComboRepository.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/FoodItemRepository.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/NotificationRepository.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/OrderRepository.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/UserRepository.java
  src/main/java/org/lafresca/lafrescabackend/Services/BranchService.java
  src/main/java/org/lafresca/lafrescabackend/Services/CartService.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodComboService.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodItemService.java
  src/main/java/org/lafresca/lafrescabackend/Services/NotificationService.java
  src/main/java/org/lafresca/lafrescabackend/Services/OrderService.java
  src/main/java/org/lafresca/lafrescabackend/Services/StockCollectionService.java
  src/main/java/org/lafresca/lafrescabackend/Services/StockService.java
  src/main/java/org/lafresca/lafrescabackend/Services/UserService.java
Labels: enhancement, feat

#134 feat: Get All Stocks and Get All Stock Collections
  src/main/java/org/lafresca/lafrescabackend/Controllers/StockCollectionController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/StockController.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/StockCollectionRepository.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/StockRepository.java
  src/main/java/org/lafresca/lafrescabackend/Services/StockCollectionService.java
  src/main/java/org/lafresca/lafrescabackend/Services/StockService.java
Labels: feat

#135 fix: Get All Branches
  src/main/java/org/lafresca/lafrescabackend/Controllers/BranchController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/FoodComboController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/FoodItemController.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/BranchRepository.java
  src/main/java/org/lafresca/lafrescabackend/Services/BranchService.java
  src/main/java/org/lafresca/lafrescabackend/Services/DiscountService.java
  src/main/java/org/lafresca/lafrescabackend/Services/EmailService.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodComboService.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodItemService.java
  src/main/java/org/lafresca/lafrescabackend/Services/StockCollectionService.java
  src/main/java/org/lafresca/lafrescabackend/Services/StockService.java
Labels: fix

#147 feat: Send OTP, Monthly Statement, Online Order Invoice and Ongoing Discount Information Functionalities
  src/main/java/org/lafresca/lafrescabackend/Controllers/DiscountController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/EmailController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/FoodItemController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/StockCollectionController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/StockController.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/FoodComboRepository.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/FoodItemRepository.java
  src/main/java/org/lafresca/lafrescabackend/Services/DiscountService.java
  src/main/java/org/lafresca/lafrescabackend/Services/EmailService.java
  src/main/java/org/lafresca/lafrescabackend/Services/StockCollectionService.java
  src/main/java/org/lafresca/lafrescabackend/Services/StockService.java
Labels: feat

#148 Scheduler
  pom.xml
  src/main/java/org/lafresca/lafrescabackend/Controllers/BranchController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/BranchStatController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/OrderController.java
  src/main/java/org/lafresca/lafrescabackend/LaFrescaBackendApplication.java
  src/main/java/org/lafresca/lafrescabackend/Models/MonthlyBranchStat.java
  src/main/java/org/lafresca/lafrescabackend/Orchestrator/SalesPredictionService.java
  src/main/java/org/lafresca/lafrescabackend/Orchestrator/ServiceOrchestrator.java
  src/main/java/org/lafresca/lafrescabackend/Orchestrator/StockPredictionService.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/MonthlyBranchStatRepository.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/OrderRepository.java
  src/main/java/org/lafresca/lafrescabackend/Scheduler/ScheduledTask.java
  src/main/java/org/lafresca/lafrescabackend/Services/BranchService.java
  src/main/java/org/lafresca/lafrescabackend/Services/MonthlyBranchStatService.java
  src/main/java/org/lafresca/lafrescabackend/Services/OrderService.java
Labels: enhancement, feat

#149 Complaint
  src/main/java/org/lafresca/lafrescabackend/Controllers/ComplaintController.java
  src/main/java/org/lafresca/lafrescabackend/Models/Complaint.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/ComplaintRepository.java
  src/main/java/org/lafresca/lafrescabackend/Services/ComplaintService.java
Labels: feat

#153 fix: stock and stock collection DTOs
  src/main/java/org/lafresca/lafrescabackend/DTO/StockCollectionDTO.java
  src/main/java/org/lafresca/lafrescabackend/DTO/StockCollectionDTOMapper.java
  src/main/java/org/lafresca/lafrescabackend/DTO/StockDTO.java
  src/main/java/org/lafresca/lafrescabackend/DTO/StockDTOMapper.java
Labels: fix
