Repository La-Fresca/la-fresca-backend, pull requests merged in 2024-06, with the labels that each got.

#1 Stucture of the backend
  src/main/java/org/lafresca/lafrescabackend/Models/User.java
  src/main/java/org/lafresca/lafrescabackend/Services/UserService.java
  src/main/resources/application.properties
Labels: enhancement

#3 Food items CRUD
  src/main/java/org/lafresca/lafrescabackend/Controllers/FoodController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/UserController.java
  src/main/java/org/lafresca/lafrescabackend/Exceptions/ResourceNotFoundException.java
  src/main/java/org/lafresca/lafrescabackend/Models/Food.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodService.java
Labels: feat

#4 fix: DB connection string
  src/main/resources/application.properties
Labels: enhancement

#7 User completed
  src/main/java/org/lafresca/lafrescabackend/Controllers/UserController.java
  src/main/java/org/lafresca/lafrescabackend/DTO/UserDTO.java
  src/main/java/org/lafresca/lafrescabackend/Models/User.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/UserRepository.java
  src/main/java/org/lafresca/lafrescabackend/Services/UserService.java
Labels: feat

#10 Add some validations for food items
  src/main/java/org/lafresca/lafrescabackend/Controllers/FoodController.java
  src/main/java/org/lafresca/lafrescabackend/Models/Menu.java
  src/main/java/org/lafresca/lafrescabackend/Models/Order.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodService.java
Labels: enhancement, feat

#14 fix: update food
  src/main/java/org/lafresca/lafrescabackend/Services/FoodService.java
Labels: enhancement

#17 Create and Update functionalities for Menu
  src/main/java/org/lafresca/lafrescabackend/Controllers/MenuController.java
  src/main/java/org/lafresca/lafrescabackend/Models/Menu.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/MenuRepository.java
  src/main/java/org/lafresca/lafrescabackend/Services/MenuService.java
Labels: enhancement, feat

#18 Menu crud
  src/main/java/org/lafresca/lafrescabackend/Controllers/MenuController.java
  src/main/java/org/lafresca/lafrescabackend/Models/Menu.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/MenuRepository.java
  src/main/java/org/lafresca/lafrescabackend/Services/MenuService.java
Labels: feat

#19 feat: added env
  src/main/resources/application.properties
Labels: feat

#20 Add env
  src/main/resources/application.properties
Labels: feat

#21 feat: initialize swagger UI
  pom.xml
  src/main/java/org/lafresca/lafrescabackend/Configuration/SwaggerConfiguration.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/FoodController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/UserController.java
  src/main/java/org/lafresca/lafrescabackend/Services/UserService.java
  src/main/resources/application.properties
Labels: feat

#22 Initialize swagger UI
  pom.xml
  src/main/java/org/lafresca/lafrescabackend/Configuration/SwaggerConfiguration.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/FoodController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/UserController.java
  src/main/java/org/lafresca/lafrescabackend/Services/UserService.java
  src/main/resources/application.properties
Labels: feat

#23 feat: setup for menu and food controllers
  src/main/java/org/lafresca/lafrescabackend/Controllers/FoodController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/MenuController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/UserController.java
Labels: feat

#24 Setup for menu and food controllers
  src/main/java/org/lafresca/lafrescabackend/Controllers/FoodController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/MenuController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/UserController.java
Labels: feat

#25 Order
  src/main/java/org/lafresca/lafrescabackend/Controllers/OrderController.java
  src/main/java/org/lafresca/lafrescabackend/Models/AddedFeature.java
  src/main/java/org/lafresca/lafrescabackend/Models/Order.java
  src/main/java/org/lafresca/lafrescabackend/Models/OrderFood.java
  src/main/java/org/lafresca/lafrescabackend/Models/OrderStatus.java
  src/main/java/org/lafresca/lafrescabackend/Models/OrderType.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/OrderRepository.java
  src/main/java/org/lafresca/lafrescabackend/Services/OrderService.java
  src/main/java/org/lafresca/lafrescabackend/Services/UserService.java
  src/main/java/org/lafresca/lafrescabackend/Validations/EmailValidation.java
  src/main/java/org/lafresca/lafrescabackend/Validations/FoodAmountValidation.java
  src/main/java/org/lafresca/lafrescabackend/Validations/UserValidation.java
  src/main/resources/application.properties
Labels: feat

#26 Added category for food items
  src/main/java/org/lafresca/lafrescabackend/Models/Food.java
Labels: enhancement, feat

#28 Branch CRUD
  src/main/java/org/lafresca/lafrescabackend/Controllers/BranchController.java
  src/main/java/org/lafresca/lafrescabackend/Models/Branch.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/BranchRepository.java
  src/main/java/org/lafresca/lafrescabackend/Services/BranchService.java
Labels: feat

#29 fix: Update Food items
  src/main/java/org/lafresca/lafrescabackend/DTO/UserDTO.java
  src/main/java/org/lafresca/lafrescabackend/Models/Food.java
  src/main/java/org/lafresca/lafrescabackend/Models/Menu.java
  src/main/java/org/lafresca/lafrescabackend/Models/User.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodService.java
Labels: enhancement

#31 fix: Update Menu
  src/main/java/org/lafresca/lafrescabackend/Services/MenuService.java
Labels: enhancement

#32 feat: Online and offline order CRUD, and Branch CRUD | fix: updateFoods and updateMenu functions
  src/main/java/org/lafresca/lafrescabackend/Controllers/BranchController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/OrderController.java
  src/main/java/org/lafresca/lafrescabackend/DTO/UserDTO.java
  src/main/java/org/lafresca/lafrescabackend/Models/AddedFeature.java
  src/main/java/org/lafresca/lafrescabackend/Models/Branch.java
  src/main/java/org/lafresca/lafrescabackend/Models/Food.java
  src/main/java/org/lafresca/lafrescabackend/Models/Menu.java
  src/main/java/org/lafresca/lafrescabackend/Models/Order.java
  src/main/java/org/lafresca/lafrescabackend/Models/OrderFood.java
  src/main/java/org/lafresca/lafrescabackend/Models/OrderStatus.java
  src/main/java/org/lafresca/lafrescabackend/Models/OrderType.java
  src/main/java/org/lafresca/lafrescabackend/Models/User.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/BranchRepository.java
  src/main/java/org/lafresca/lafrescabackend/Repositories/OrderRepository.java
  src/main/java/org/lafresca/lafrescabackend/Services/BranchService.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodService.java
  src/main/java/org/lafresca/lafrescabackend/Services/MenuService.java
  src/main/java/org/lafresca/lafrescabackend/Services/OrderService.java
  src/main/java/org/lafresca/lafrescabackend/Services/UserService.java
  src/main/java/org/lafresca/lafrescabackend/Validations/EmailValidation.java
  src/main/java/org/lafresca/lafrescabackend/Validations/FoodAmountValidation.java
  src/main/java/org/lafresca/lafrescabackend/Validations/UserValidation.java
  src/main/resources/application.properties
Labels: enhancement, feat

#34 refactor: collection names and order attributes
  src/main/java/org/lafresca/lafrescabackend/Controllers/OrderController.java
  src/main/java/org/lafresca/lafrescabackend/Models/CustomFeature.java
  src/main/java/org/lafresca/lafrescabackend/Models/FoodCombo.java
  src/main/java/org/lafresca/lafrescabackend/Models/FoodItem.java
  src/main/java/org/lafresca/lafrescabackend/Models/Order.java
  src/main/java/org/lafresca/lafrescabackend/Services/OrderService.java
Labels: refactor

#35 fix: Branch CRUD Functionalities
  src/main/java/org/lafresca/lafrescabackend/Models/Branch.java
  src/main/java/org/lafresca/lafrescabackend/Services/BranchService.java
Labels: fix

#37 fix: updateFoodCombo and updateFoodItem functions | refactor: all methods of FoodCombo and FoodItem classes
  src/main/java/org/lafresca/lafrescabackend/Controllers/FoodComboController.java
  src/main/java/org/lafresca/lafrescabackend/Controllers/FoodItemController.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodComboService.java
  src/main/java/org/lafresca/lafrescabackend/Services/FoodItemService.java
Labels: refactor, fix
